### ISSUE TITLE
Buggy jump from location to location

### ISSUE THREAD

**Issue by clemensschlipfinger** [TooMuchBrainProjects/raspberry-globe#2]
it is a bit buggy when jumping to new location

**Comment by trueberryless** [comment]
bruh, i literally wanted to create this issue right now

**Comment by clemensschlipfinger** [comment]
Das Problem liegt darin, dass das Web Frontend immer die Weather-Daten fetched, welche verzögert beim Client ankommen

**Comment by clemensschlipfinger** [comment]
I would recommend to use the async/await syntax instead of the callback methods (hehe)

**Comment by trueberryless** [comment]
I can quick fix it by setting the intervall to 1200ms...

**Comment by trueberryless** [comment]
Okay, he doesn't want to

**Comment by trueberryless** [comment]
Async suiii
